name: Release

on:
  push:
    tags:
      - 'v*'  # v0.1.0 같은 태그 푸시 시 실행

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/ui   # 패키지 디렉터리 기준으로 실행
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # 홈 디렉토리 ~/.npmrc에 토큰 주입 (패키지 디렉토리의 .npmrc보다 우선순위가 낮음)
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 루트 .npmrc가 registry를 바꿔놓았다면 충돌 방지
      - name: Ensure npmjs registry locally
        run: |
          if [ -f .npmrc ]; then mv .npmrc .npmrc.backup; fi
          echo "registry=https://registry.npmjs.org" > .npmrc

      - run: npm ci
      - run: npm test --if-present

      # 스코프 공개 패키지라면 publishConfig.access 확인
      - name: Check publishConfig
        run: node -e "const p=require('./package.json'); if(p.name?.startsWith('@') && (!p.publishConfig || p.publishConfig.access!=='public')){ process.exit(1) }"

      - name: Publish to npm
        run: npm publish
