name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # npmjs 발행만 쓸 때:
          registry-url: https://registry.npmjs.org/
          # GitHub Packages/사내 레지스트리를 스코프 기반으로 쓰면
          # registry-url 생략 가능(루트 .npmrc가 처리)

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version-packages
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
